### ISSUE TITLE
How to modify the template we're using?

### ISSUE THREAD

**Issue by sole** [firefox-devtools/firefox-devtools.github.io#8]
I'd like to have some sort of navigation bar, etc. Right now we're using a template from jekyll (?) so I do not know how to edit this or the appearance etc.

**Comment by clarkbw** [comment]
I found this about changing themes and customizing themes https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/

**Comment by sole** [comment]
Thanks!

I like https://github.com/jekyll/minima - looks like https://jekyll.github.io/minima/
It has a sort of top nav bar!

We could use it to get started, although ideally we would want to have some mozilla/devtools themed stuff, I guess!

**Comment by sole** [comment]
Customising here: https://help.github.com/articles/customizing-css-and-html-in-your-jekyll-theme/
